"""
ScreenAlert MCP Server

Runs as a daemon thread inside the ScreenAlert process.
Exposes tools, prompts, and resources to any MCP-compliant client
(Claude Desktop, Claude Code, etc.) over HTTPS/SSE on localhost.

Transport:  HTTPS  (self-signed cert auto-generated by tls.py)
Auth:       Bearer token in Authorization header
Endpoints:
    /v1/sse        SSE transport  (MCP 2024-11-05)
    /v1/mcp        Streamable HTTP (MCP 2025-03-26)
    /v1/health     Health check
    /v1/status     Server diagnostics
    /v1/skills     Tool introspection
    /v1/resources/ Capture file browser
"""

import json
import logging
import os
import secrets
import threading
import time
from typing import Any, Callable, Dict, Optional

logger = logging.getLogger(__name__)


class MCPServer:
    """
    Embedded HTTPS MCP server.

    Usage:
        server = MCPServer(engine=engine, config=config, event_logger=el)
        server.start()
        # ... app runs ...
        server.stop()
    """

    def __init__(self, engine: Any, config: Any, event_logger: Any):
        self._engine = engine
        self._config = config
        self._event_logger = event_logger

        self._uvicorn_server: Optional[Any] = None
        self._thread: Optional[threading.Thread] = None
        self._start_time: Optional[float] = None
        self._active_connections: int = 0
        self._conn_lock = threading.Lock()

        # Auth failure rate-limiting: source -> last-logged timestamp
        self._auth_fail_ts: Dict[str, float] = {}
        self._auth_fail_lock = threading.Lock()

        self._mcp: Optional[Any] = None  # FastMCP instance, built in start()

    # ── Lifecycle ─────────────────────────────────────────────────────────────

    def start(self) -> None:
        """Start the HTTPS MCP server on a daemon thread."""
        if not self._config.get_mcp_enabled():
            logger.info("MCP server is disabled (mcp_enabled=false)")
            return

        self._ensure_api_key()
        self._ensure_cert()

        app = self._build_app()

        port = self._config.get_mcp_port()
        cert = self._config.get_mcp_ssl_cert_path()
        key = self._config.get_mcp_ssl_key_path()

        try:
            import uvicorn
            uconfig = uvicorn.Config(
                app=app,
                host="127.0.0.1",
                port=port,
                ssl_certfile=cert,
                ssl_keyfile=key,
                log_level="warning",
                loop="asyncio",
            )
            self._uvicorn_server = uvicorn.Server(uconfig)
            self._start_time = time.time()

            self._thread = threading.Thread(
                target=self._uvicorn_server.run,
                daemon=True,
                name="MCPServer",
            )
            self._thread.start()
            logger.info("MCP server started on https://127.0.0.1:%s/v1", port)

            if self._config.get_mcp_http_redirect():
                self._start_http_redirect()

        except Exception as exc:
            logger.error("MCP server failed to start: %s", exc, exc_info=True)

    def stop(self) -> None:
        """Gracefully stop the server."""
        if self._uvicorn_server:
            self._uvicorn_server.should_exit = True
        if self._thread:
            self._thread.join(timeout=5)
        logger.info("MCP server stopped")

    def is_running(self) -> bool:
        return self._thread is not None and self._thread.is_alive()

    def active_connections(self) -> int:
        with self._conn_lock:
            return self._active_connections

    # ── App construction ──────────────────────────────────────────────────────

    def _build_app(self) -> Any:
        from mcp.server.fastmcp import FastMCP
        from starlette.applications import Starlette
        from starlette.middleware import Middleware
        from starlette.middleware.base import BaseHTTPMiddleware
        from starlette.requests import Request
        from starlette.responses import JSONResponse, Response
        from starlette.routing import Mount, Route

        self._mcp = FastMCP(
            "ScreenAlert",
            instructions=(
                "ScreenAlert monitors application windows and fires alerts when "
                "screen regions change. Use list_windows and list_regions to discover "
                "what is being monitored. Call ping first to verify connectivity."
            ),
        )
        self._register_tools()
        self._register_prompts()

        api_key = self._config.get_mcp_api_key()
        max_conns = self._config.get_mcp_max_connections()
        server_ref = self  # closure reference

        class AuthMiddleware(BaseHTTPMiddleware):
            async def dispatch(self, request: Request, call_next: Callable) -> Response:
                # Health endpoint is always public — clients use it to check reachability
                if request.url.path == "/v1/health":
                    return await call_next(request)

                auth = request.headers.get("Authorization", "")
                if not auth.startswith("Bearer ") or auth[7:] != api_key:
                    source = request.client.host if request.client else "unknown"
                    server_ref._log_auth_failure(source)
                    return JSONResponse(
                        {"error": "Invalid or missing API key", "code": 401},
                        status_code=401,
                    )
                return await call_next(request)

        class ConnectionLimitMiddleware(BaseHTTPMiddleware):
            async def dispatch(self, request: Request, call_next: Callable) -> Response:
                # Only count SSE/MCP persistent connections
                is_sse = request.url.path.endswith("/sse")
                if is_sse:
                    with server_ref._conn_lock:
                        if server_ref._active_connections >= max_conns:
                            return JSONResponse(
                                {"error": "Too many connections", "code": 429},
                                status_code=429,
                            )
                        server_ref._active_connections += 1
                try:
                    return await call_next(request)
                finally:
                    if is_sse:
                        with server_ref._conn_lock:
                            server_ref._active_connections = max(
                                0, server_ref._active_connections - 1
                            )

        async def handle_health(request: Request) -> JSONResponse:
            return JSONResponse({"status": "ok"})

        async def handle_status(request: Request) -> JSONResponse:
            from screenalert_core.mcp.tls import cert_fingerprint, cert_expiry
            cert_path = self._config.get_mcp_ssl_cert_path()
            uptime = int(time.time() - self._start_time) if self._start_time else 0
            return JSONResponse({
                "status": "ok",
                "version": self._app_version(),
                "uptime_seconds": uptime,
                "active_connections": self.active_connections(),
                "max_connections": max_conns,
                "cert_fingerprint": cert_fingerprint(cert_path),
                "cert_expires": cert_expiry(cert_path),
                "event_log_enabled": self._config.get_event_log_enabled(),
                "monitoring_state": self._monitoring_state(),
            })

        async def handle_skills(request: Request) -> JSONResponse:
            tools = await self._mcp.list_tools()
            skills = [
                {
                    "name": t.name,
                    "description": t.description or "",
                    "parameters": t.inputSchema if hasattr(t, "inputSchema") else {},
                }
                for t in tools
            ]
            return JSONResponse(skills)

        async def handle_resources_index(request: Request) -> Response:
            from starlette.responses import HTMLResponse
            capture_dir = self._config.get_capture_dir() if hasattr(self._config, "get_capture_dir") else ""
            html = self._build_resource_browser_html(capture_dir)
            return HTMLResponse(html)

        async def handle_resource_file(request: Request) -> Response:
            from starlette.responses import FileResponse, Response as StarResponse
            path_param = request.path_params.get("path", "")
            capture_dir = self._config.get_capture_dir() if hasattr(self._config, "get_capture_dir") else ""
            full_path = os.path.normpath(os.path.join(capture_dir, path_param))
            # Security: ensure the resolved path stays within capture_dir
            if not full_path.startswith(os.path.normpath(capture_dir)):
                return JSONResponse({"error": "Access denied", "code": 403}, status_code=403)
            if not os.path.isfile(full_path):
                return JSONResponse({"error": "File not found", "code": 404}, status_code=404)
            return FileResponse(full_path)

        routes = [
            Route("/v1/health", handle_health),
            Route("/v1/status", handle_status),
            Route("/v1/skills", handle_skills),
            Route("/v1/resources", handle_resources_index),
            Route("/v1/resources/{path:path}", handle_resource_file),
            Mount("/v1", app=self._mcp.sse_app()),
            Mount("/v1/mcp", app=self._mcp.streamable_http_app()),
        ]

        app = Starlette(
            routes=routes,
            middleware=[
                Middleware(AuthMiddleware),
                Middleware(ConnectionLimitMiddleware),
            ],
        )
        return app

    # ── Tool & prompt registration ─────────────────────────────────────────────

    def _register_tools(self) -> None:
        """Register all MCP tools."""
        self._register_utility_tools()
        from screenalert_core.mcp.tools import windows as _windows_mod
        from screenalert_core.mcp.tools import regions as _regions_mod
        _windows_mod.register(self._mcp, self._engine, self._config, self._event_logger)
        _regions_mod.register(self._mcp, self._engine, self._config, self._event_logger)
        from screenalert_core.mcp.tools import monitoring as _monitoring_mod
        from screenalert_core.mcp.tools import settings as _settings_mod
        _monitoring_mod.register(self._mcp, self._engine, self._config, self._event_logger)
        _settings_mod.register(self._mcp, self._engine, self._config, self._event_logger)
        from screenalert_core.mcp.tools import event_log as _event_log_mod
        from screenalert_core.mcp.tools import images as _images_mod
        _event_log_mod.register(self._mcp, self._engine, self._config, self._event_logger)
        _images_mod.register(self._mcp, self._engine, self._config, self._event_logger)

    def _register_utility_tools(self) -> None:
        import time as _time

        engine = self._engine
        config = self._config

        @self._mcp.tool(
            description=(
                "Verify connectivity and retrieve basic server information. "
                "Call this first to confirm the MCP server is reachable and get "
                "the app version, TLS certificate fingerprint, and monitoring state."
            )
        )
        def ping() -> Dict:
            """Returns server version, uptime, cert fingerprint, and monitoring state."""
            from screenalert_core.mcp.tls import cert_fingerprint
            cert_path = config.get_mcp_ssl_cert_path()
            uptime = int(_time.time() - self._start_time) if self._start_time else 0
            return {
                "version": self._app_version(),
                "uptime_seconds": uptime,
                "cert_fingerprint": cert_fingerprint(cert_path),
                "monitoring_state": self._monitoring_state(),
            }

    def _register_prompts(self) -> None:
        """Register MCP prompt templates."""

        @self._mcp.prompt(
            description="Summarise and interpret recent ScreenAlert activity"
        )
        def analyse_alert_history(
            since: str = "",
            window_name: str = "",
        ) -> str:
            parts = ["Please analyse the ScreenAlert event log"]
            if since:
                parts.append(f"from {since} onwards")
            if window_name:
                parts.append(f"for window '{window_name}'")
            parts.append(
                ". Call get_event_summary to get counts, then get_event_log "
                "to see details. Highlight any patterns, frequent alerts, or "
                "windows that look problematic."
            )
            return " ".join(parts)

        @self._mcp.prompt(
            description="Check all windows and regions and report anything that needs attention"
        )
        def what_needs_attention() -> str:
            return (
                "Please check the current state of ScreenAlert. "
                "Call list_windows to see all monitored windows and their connection status. "
                "Call list_alerts to see any active alerts. "
                "Call get_monitoring_status to check if monitoring is running. "
                "Report anything that looks wrong or needs attention."
            )

        @self._mcp.prompt(
            description="Retrieve and show recent alert screenshots"
        )
        def show_recent_captures(window_name: str = "") -> str:
            base = "Please show me recent alert captures"
            if window_name:
                base += f" for window '{window_name}'"
            return (
                base + ". Call get_event_log with category='alert' to find recent "
                "alert events that have capture_file set, then call get_alert_image "
                "for each one so I can see what triggered them."
            )

        @self._mcp.prompt(
            description="Diagnose a specific window's connection, regions, and recent history"
        )
        def diagnose_window(window_name: str) -> str:
            return (
                f"Please diagnose the window '{window_name}' in ScreenAlert. "
                "Call get_window_settings to see its configuration. "
                "Call list_regions with that window to see all its monitoring regions. "
                "Call get_event_log filtered to that window to see recent events. "
                "Summarise the window's health and any issues you find."
            )

        @self._mcp.prompt(
            description="Produce a full activity report for today"
        )
        def daily_summary() -> str:
            import datetime
            today = datetime.date.today().isoformat()
            return (
                f"Please produce a daily activity summary for ScreenAlert for {today}. "
                "Call get_event_summary with since set to today's date. "
                "Then call get_event_log filtered to today's alerts. "
                "Include: total events, alert counts per window, any windows that "
                "disconnected, and settings changes made today."
            )

    # ── HTTP redirect ──────────────────────────────────────────────────────────

    def _start_http_redirect(self) -> None:
        """Start a plain-HTTP listener that 301-redirects all traffic to HTTPS."""
        http_port = self._config.get_mcp_http_port()
        https_port = self._config.get_mcp_port()

        from starlette.applications import Starlette
        from starlette.requests import Request
        from starlette.responses import RedirectResponse
        from starlette.routing import Route
        import uvicorn

        async def redirect_all(request: Request) -> RedirectResponse:
            url = str(request.url).replace(
                f"http://", "https://", 1
            ).replace(f":{http_port}", f":{https_port}", 1)
            return RedirectResponse(url, status_code=301)

        redirect_app = Starlette(routes=[Route("/{path:path}", redirect_all)])
        uconfig = uvicorn.Config(
            app=redirect_app,
            host="127.0.0.1",
            port=http_port,
            log_level="warning",
            loop="asyncio",
        )
        redirect_server = uvicorn.Server(uconfig)
        t = threading.Thread(target=redirect_server.run, daemon=True, name="MCPRedirect")
        t.start()
        logger.info("MCP HTTP redirect started on port %s → https port %s", http_port, https_port)

    # ── Helpers ───────────────────────────────────────────────────────────────

    def _ensure_api_key(self) -> None:
        """Generate and persist an API key if one doesn't exist."""
        if not self._config.get_mcp_api_key():
            key = secrets.token_hex(32)
            self._config.set_mcp_api_key(key)
            self._config.save()
            logger.info("Generated new MCP API key")

    def _ensure_cert(self) -> None:
        """Ensure TLS cert and key exist, generating them if needed."""
        from screenalert_core.mcp.tls import ensure_cert
        from screenalert_core.utils.constants import MCP_CERT_FILE, MCP_KEY_FILE

        cert_path = self._config.get_mcp_ssl_cert_path() or MCP_CERT_FILE
        key_path = self._config.get_mcp_ssl_key_path() or MCP_KEY_FILE

        ensure_cert(cert_path, key_path)

        if not self._config.get_mcp_ssl_cert_path():
            self._config.set_mcp_ssl_cert_path(cert_path)
            self._config.set_mcp_ssl_key_path(key_path)
            self._config.save()

    def _log_auth_failure(self, source: str) -> None:
        """Log auth failures at most once per source per 60 seconds."""
        now = time.time()
        with self._auth_fail_lock:
            last = self._auth_fail_ts.get(source, 0)
            if now - last >= 60:
                self._auth_fail_ts[source] = now
                logger.debug("MCP auth failure from %s", source)

    def _app_version(self) -> str:
        try:
            from screenalert_core.utils.constants import APP_VERSION
            return APP_VERSION
        except Exception:
            return "unknown"

    def _monitoring_state(self) -> str:
        try:
            if hasattr(self._engine, "running") and not self._engine.running:
                return "stopped"
            if hasattr(self._engine, "paused") and self._engine.paused:
                return "paused"
            return "running"
        except Exception:
            return "unknown"

    def _build_resource_browser_html(self, capture_dir: str) -> str:
        """Build a simple HTML file listing for the captures directory."""
        if not capture_dir or not os.path.isdir(capture_dir):
            return "<html><body><p>No captures directory configured.</p></body></html>"

        files = []
        for root, _, filenames in os.walk(capture_dir):
            for fname in sorted(filenames):
                full = os.path.join(root, fname)
                rel = os.path.relpath(full, capture_dir).replace("\\", "/")
                size = os.path.getsize(full)
                files.append((rel, size))

        rows = "".join(
            f'<tr><td><a href="/v1/resources/{rel}">{rel}</a></td>'
            f'<td>{size:,} bytes</td></tr>'
            for rel, size in files
        )
        return (
            "<html><head><title>ScreenAlert Captures</title></head><body>"
            "<h2>ScreenAlert Captures</h2>"
            f"<table border='1' cellpadding='4'><tr><th>File</th><th>Size</th></tr>"
            f"{rows}</table></body></html>"
        )
